# Generated by Django 6.0 on 2025-12-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Название марки автомобиля (например, Toyota, BMW)', max_length=100, verbose_name='Марка')),
                ('model', models.CharField(help_text='Название модели автомобиля (например, Camry, X5)', max_length=100, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(help_text='Год выпуска автомобиля', verbose_name='Год выпуска')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена автомобиля в рублях', max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['-year', 'brand', 'model'],
            },
        ),
    ]
