# Generated by Django 6.0 on 2025-12-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_pr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='price',
        ),
    ]
